Update install (removed explicit pull, as implied by distrobox create)

diff --git a/install b/install
--- a/install
+++ b/install
@@ -46,12 +46,12 @@ if ! command -v distrobox > /dev/null; then
     fi
 fi
 
-log "Pulling ROS image..."
-sudo podman pull ghcr.io/misabthepro/ros-humble-toolbox:latest # or use this image "ghcr.io/misabthepro/ros-humble-toolbox:latest"
-if [ $? -ne 0 ]; then
-    error "Error: Podman image pull failed. Please try again."
-    exit 1
-fi
+# log "Pulling ROS image..."
+# sudo podman pull ghcr.io/misabthepro/ros-humble-toolbox:latest # or use this image "ghcr.io/misabthepro/ros-humble-toolbox:latest"
+# if [ $? -ne 0 ]; then
+#     error "Error: Podman image pull failed. Please try again."
+#     exit 1
+# fi
 
 log "Creating Distrobox environment..."
 distrobox rm ros2 --root -f > /dev/null 2>&1
